version: 0.2


phases:
    install:
        commands: 
            - pip install checkov
            
    pre_install:
        commands:
            - ls
            - printenv
            
    build:
        commands:
            - ls
            - cat s3.yml
            
    post_build:
        commands:
            - ls
            
    